name: Mi primer Workflow
on: workflow_dispatch
jobs:
  mi-primer-job:
    runs-on: ubuntu-latest
    steps:
      - name: imprimir saludo
        run: echo "Hola mundo con github Actions"
      - name: imprimir saludo
        run: echo "Listo. !AdiosÂ¡"
